/* Generated By:JJTree: Do not edit this line. ASTCallbackNode.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jcc2.parser;

public
class ASTCallbackNode extends SimpleNode {
  public ASTCallbackNode(int id) {
    super(id);
  }

  public ASTCallbackNode(Jcc2Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=eb69ef5c65156c180f1fe2cd91bffc2d (do not edit this line) */
